# -*- encoding: utf-8 -*-

{
    "name": "Punto de Venta Ecuatoriano",
    "version": "1.0",
    "depends": [
        'base',
        'point_of_sale',
        'ec_sri_authorizathions',
        'base_address_extended',
        'pos_discount',
        'account_cash_deposit',
        'pos_daily_sales_reports',
        'report_xlsx',
    ],
    "author": "",
    "website": "https://",
    "category": "Development Tools",
    "complexity": "normal",
    "description": """ Personaliza el TPV para Ecuador """,
    "init_xml": [],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_config_view.xml',
        'views/pos_order_view.xml',
        'views/pos_res_config_view.xml',
        'views/pos_payment_view.xml',
        'views/pos_session_view.xml',
        'views/account_cash_deposit_view.xml',
        'views/pos_payment_method_views.xml',
        'views/stock_picking_views.xml',
        'views/report_saledetails_override.xml',
        'views/pos_details_wizard_override.xml',
        'data/server_actions.xml',
    ],
    'assets': {
        'point_of_sale.assets': [
            'ec_pos/static/src/js/pos_models.js',
            'ec_pos/static/src/js/pos_partner.js',
            'ec_pos/static/src/js/SurchargeSelectionPopup.js',
            'ec_pos/static/src/js/PaymentScreen.js',
            'ec_pos/static/src/xml/PaymentScreen.xml',
            'ec_pos/static/src/js/PartnerListScreen.js',
            'ec_pos/static/src/js/TicketScreen.js',
            'ec_pos/static/src/js/OrderSummaryLegacy.js',
            'ec_pos/static/src/js/ClosePosPopup.js',
            'ec_pos/static/src/js/Screens/ProductScreen/NumpadWidget.js',
            'ec_pos/static/src/xml/**/*',
            # 'ec_pos/static/src/xml/order_receipt.xml',

        ],
    },
    'demo_xml': [],
    'test': [],
    'installable': True,
    'auto_install': False,
    'license': 'LGPL-3',
}
