# -*- coding: utf-8 -*-
{
    'name' : 'EC Recursos Humanos',
    'version' : '1.0',
    'author' : '',
    'category' : 'Recursos Humanos',
    'sequence': 10,
    'description' : "",

    'images' : [
    ],

    'depends' : [
        'base',
        'account',
        'account_fiscal_year',
        'account_followup',
        'account_auto_transfer',
        'ec_payment_check',
        'ec_tools',
        'ec_account_edi',
        'ec_account_base',
        'ec_cash',
        'history_employee',
        'hr',
        'hr_contract',
        'hr_expense',
        'hr_holidays',
        'hr_payroll',
        'hr_payroll_account',
        'report_xlsx',
        'mail',
        'ec_ats',
        'analytic',
        'hr_work_entry_contract_enterprise',
    ],
    'data': [
        'data/ir_rule.xml',
        'security/ir.model.access.csv',
        # 'security/rules.xml',
        'security/groups.xml',
        # 'data/rules.xml',
        'data/rules_data.xml',
        'data/sequence_data.xml',
        'data/expense_paperformat.xml',
        'data/request_overtime_data.xml',
        'data/egress_request_data.xml',
        'data/role_paperformat.xml',
        'data/request_overtime_paperformat.xml',
        'data/contract_data.xml',
        'data/hr_liquidation_data.xml',
        'data/contract_finish_mail.xml',
        # 'data/fiscal_year_data.xml',
        # 'data/table_ir_data.xml',
        # 'report/reports_expense.xml',
        'report/payrole_report.xml',
        'report/reporte_nominas_x_departamentos.xml',
        'report/reporte_nominas_x_departamentos_a3.xml',
        'report/reports_request_overtime.xml',
        'report/reports_request_egress.xml',
        'report/report_request_loan_payment.xml',
        'report/report_hr_liquidation.xml',
        'wizard/wizard_pay_batch_slip_view.xml',
        'wizard/payslip_by_employee_view.xml',
        'wizard/wizard_request_egress_show_payslip_detail.xml',
        'wizard/print_rol_format_view.xml',
        'wizard/cen_expense_load_wizard_view.xml',
        'views/root_menu.xml',
        'views/analisis_lineas_nomina_view.xml',
        'views/employee_view.xml',
        'views/payment_view.xml',
        'views/contract_view.xml',
        'views/rule_view.xml',
        'views/structure_view.xml',
        'views/scheduled_transaction_view.xml',
        'views/slip_view.xml',
        'views/batch_slip_view.xml',
        'views/res_config.xml',
        'views/impuesto_renta_view.xml',
        'views/family_burden_view.xml',
        # 'views/expense_view.xml',
        'views/request_overtime_view.xml',
        # 'views/holiday_view.xml',
        'views/request_egress_view.xml',
        'views/request_loan_payment_view.xml',
        'views/company_view.xml',
        'views/vacations_view.xml',
        'views/subsidy_view.xml',
        'views/hr_liquidation_view.xml',
        'views/generate_filebb_wizard.xml',
        'views/department_view.xml',
        'views/provision_view.xml',
        'views/contract_type_rules.xml',
        # 'data/rol_send_mail.xml'
        # 'views/request_loan_inherit_views.xml',
        'views/hr_payment_view.xml',
        'views/res_config.xml',
        'wizard/wizard_report_deduction.xml',
        'wizard/wizard_report_other_inputs.xml',
        'wizard/wizard_report_vacations.xml',
        'wizard/wizard_report_loans.xml',
        'wizard/wizard_report_advance.xml',
        'wizard/wizard_report_employee_account_bank.xml',
        'wizard/wizard_report_employee_accumulated_benefits.xml',
        'wizard/wizard_report_salary_history.xml',
        'wizard/wizard_report_employee_type_contract.xml',
        'wizard/wizard_report_pending_vacations.xml',
        'wizard/wizard_report_advantage_social.xml',
        'wizard/wizard_report_income_tax.xml',
        'wizard/wizard_report_employee_withholding.xml',
        'wizard/wizard_report_employee_general.xml',
        'wizard/wizard_report_loan_payment.xml',
        'wizard/wizard_report_tenths.xml',
        'wizard/wizard_report_request_overtime.xml',
        'wizard/wizard_report_employee_simplified.xml',
        'report/report_deduction.xml',
        'report/report_other_inputs.xml',
        'report/report_vacations.xml',
        'report/report_loans.xml',
        'report/report_employee_account_bank.xml',
        'report/report_employee_accumulated_benefits.xml',
        'report/report_salary_history.xml',
        'report/report_employee_type_contract.xml',
        'report/report_pending_vacations.xml',
        'report/report_advantage_social.xml',
        'report/report_income_tax.xml',
        'report/report_employee_general.xml',
        'report/report_loan_payment.xml',
        'report/report_tenths.xml',
        'report/report_advance.xml',
    ],
    'qweb' : [
    ],
    'demo': [
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
